# reusable workflow - `production` environment

on:
  workflow_call

concurrency:
  group: production-deployment

jobs:
  build-deploy:
    name: Build Docker image and push to ECR, Deploy to ECS
    environment: production
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.build-image.outputs.image }}

    permissions:
      id-token: write

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials (for ECR)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_ECR_ROLE_TO_ASSUME }}
        aws-region: ${{ vars.AWS_REGION }}
        mask-aws-account-id: false

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ vars.AMY_ECR_REPO_NAME }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA" >> $GITHUB_OUTPUT

    - name: Configure AWS Credentials (for ECS)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_ECS_ROLE_TO_ASSUME }}
        aws-region: ${{ vars.AWS_REGION }}
        mask-aws-account-id: false

    - name: Download task definition
      env:
        TASK_DEFINITION_FAMILY: ${{ vars.AMY_ECS_TASK_DEFINITION_FAMILY }}
      run: |
        aws ecs describe-task-definition --task-definition $TASK_DEFINITION_FAMILY --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ vars.AMY_ECS_TASK_DEFINITION_CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ vars.AMY_ECS_SERVICE_NAME }}
        cluster: ${{ vars.AMY_ECS_CLUSTER_NAME }}
        force-new-deployment: true
        wait-for-service-stability: true
